services:
  # MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ~/workspaces/data/mysql:/var/lib/mysql
    networks:
      - spring-cloud-network

  # Redis
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ~/workspaces/data/redis:/data
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local